---
vector_version: "0.33.0"
vector_config:
  sources:
    log_file:
      type: file
      include:
        - etc/vector/*.log"
      read_from: beginning
  sinks:
      clickhouse:
        type: clickhouse
        inputs: 
          - log_file
        table: my_table
        compression: gzip
        database: logs
        endpoint: http://51.250.30.255:8123
        skip_unknown_fields: true
        healthcheck: false
