version: '3.8'

services:

  debian:
    image: ubuntu
    container_name: ubuntu
    build:
      context: ubuntu
      dockerfile: Dockerfile
    networks:
      test_net:
        ipv4_address: 192.168.10.3
    tty: true

  centos7:
    image: centos:7
    container_name: centos7
    networks:
      test_net:
        ipv4_address: 192.168.10.2
    tty: true

networks:
  test_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
